# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 595)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_folder_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_folder_name.setEnabled(True)
        self.le_folder_name.setGeometry(QtCore.QRect(20, 30, 901, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.le_folder_name.setFont(font)
        self.le_folder_name.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.le_folder_name.setText("")
        self.le_folder_name.setReadOnly(True)
        self.le_folder_name.setObjectName("le_folder_name")
        self.btn_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analyze.setEnabled(False)
        self.btn_analyze.setGeometry(QtCore.QRect(170, 60, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.btn_analyze.setFont(font)
        self.btn_analyze.setObjectName("btn_analyze")
        self.btn_select_folder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select_folder.setGeometry(QtCore.QRect(20, 60, 100, 100))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.btn_select_folder.setFont(font)
        self.btn_select_folder.setObjectName("btn_select_folder")
        self.tb_information = QtWidgets.QTextBrowser(self.centralwidget)
        self.tb_information.setGeometry(QtCore.QRect(290, 60, 631, 401))
        self.tb_information.setObjectName("tb_information")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_folder_name.setPlaceholderText(_translate("MainWindow", "Выберите папку для анализа"))
        self.btn_analyze.setText(_translate("MainWindow", "Анализ"))
        self.btn_select_folder.setText(_translate("MainWindow", "Выбрать\n"
"папку"))
