# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(638, 451)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.le_folder_name = QtWidgets.QLineEdit(self.centralwidget)
        self.le_folder_name.setEnabled(True)
        self.le_folder_name.setGeometry(QtCore.QRect(20, 30, 250, 20))
        self.le_folder_name.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.le_folder_name.setReadOnly(True)
        self.le_folder_name.setObjectName("le_folder_name")
        self.btn_analyze = QtWidgets.QPushButton(self.centralwidget)
        self.btn_analyze.setGeometry(QtCore.QRect(140, 80, 100, 25))
        self.btn_analyze.setObjectName("btn_analyze")
        self.btn_select_folder = QtWidgets.QPushButton(self.centralwidget)
        self.btn_select_folder.setGeometry(QtCore.QRect(290, 29, 75, 23))
        self.btn_select_folder.setObjectName("btn_select_folder")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.le_folder_name.setText(_translate("MainWindow", "Выберите папку для анализа"))
        self.btn_analyze.setText(_translate("MainWindow", "Анализировать"))
        self.btn_select_folder.setText(_translate("MainWindow", "..."))
